Feature: Support
  Scenario: As a user, I see the support page
    Given I visit "/support"
    Then I see document title "Encrypit Support"
      And I see heading "Support"
      And I see link "support@encrypit.com"
      And I see link "issue"
      And I see link "discussion"
      And I see link "GitHub Sponsors"
      And I see link "Patreon"
      And I see link "Ko-fi"
      And I see link "Liberapay"
      And I see link "Teespring"
    When I click on link "FAQ"
    Then I see URL "/faq"
    When I go back
      And I click on link "Privacy Policy"
    Then I see URL "/privacy"
    When I click on label "Support"
    Then I see URL "/support"
