name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Lint commit messages
        run: yarn commitlint --from=HEAD~1

      - name: Run ESLint
        run: yarn lint

      - name: Type check
        run: yarn lint:tsc

      - name: Run Jest tests
        run: yarn test:ci

      - name: Build app
        run: yarn build
