name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint commit messages
        run: npx commitlint --from=HEAD~1

      - name: Run ESLint
        run: npm run lint

      - name: Type check
        run: npm run lint:tsc

      - name: Run Jest tests
        run: npm run test:ci

      - name: Build app
        run: npm run build

      - name: Codecov
        uses: codecov/codecov-action@v3
