name: cypress
on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: |
            yarn vite --host
            yarn server
          wait-on: 'http://localhost:5173, http://localhost:8788'

      - name: Record failed screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Record videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
